---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbird-operator-kubernetes-operator
  namespace: netbird
spec:
  encryptedData:
    NB_API_KEY: AgA2DIJ4nlJtkAeM/dusmJst0HOGYtZAcSfHexqYxzRFw51MNvTwIOJi2zKTuOebfkxpLx09FyETyr8NExxBZdLjnJ7LanBlUFAYcAFNfk8+Un3DljitL/gaVzmtawyXuCki1DoF3srsgPSeMGwxbDT212bXGWYjPsRwGTuDyjtxJAl9vJ+MGT44Ycp266OpA4f2c0RMMBi8yKx/iE8YxyOKolTT4ajxwpX8RYyraG0GShHCEEnx6oImx1S1bhW/znY3jnBjbqs1kuOj/KHCt9fsid0QgPeVhyaeHkvnOk3m1wi2obt6P8RjmWHyNl/eh9k0QnExmxFCyA72mx2YD6y5N8B4a+TVbVySJYOYbq1ITjAVSbe82IcQOIEnkC3ucC0PWbdiK/teQPG5XflHD/vdQEne0rcySnxbJ2btBZNI5olwmPvJYga1GwDqM+a7v+lbHtUbr1qW9+qr4bS64ZYweDxaVesgbI1pIaBhQD2MeHFHkMXeFMRspJuRmM+mhIsFbB7RlQF9WI1i1fpb7p9FptCHjsgTxGF8qrKR4SoMz2asiu3mUglqL1V62KVZ2C3xzieatDDhSDpOiDbeVflH7yun3qQOnvzq7tJjyeCTvbnfpZqAlprNEO4A6C4rWUkG0VgY/RdfCthM50ttHMsyWvtZxcmtPWVd0Kc17kVlrlL7VKz85r9iEl0vRoJIr2CYVxYLHLPPcCsf8D1rzApTOrwUkaEFZdHbzTtHzkB1pYd0aY2V/OTZ
  template:
    metadata:
      name: netbird-operator-kubernetes-operator
      namespace: netbird
